name : The most expensive pitch of 2015
brand : 2015 MLB Salary/Pitch
description : How much does a MLB pitch cost? 2016 Baseball Hack Day submission
keyword : 
url : http://daigofuji.github.io/expensive-pitches/
email : daigo@daigofujiwara.com
twitter : DaigoFuji
github : DaigoFuji
author : Daigo Fujiwara
analytics : UA-8418273-8
year : 2016
markdown : kramdown
exclude :
  - node_modules
